# PACKAGE_MANAGER
- name: Disable proxmox enterprise apt repository
  tags: package_manager
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regex: 'deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'
    line: '# deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'

- name: Disable Ceph enterprise apt repository
  tags: package_manager
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/ceph.list
    regex: 'deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise'
    line: '# deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise'

- name: Add proxmox non subscription apt repository
  tags: package_manager
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    regex: 'deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription'
    line: 'deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription'
    insertafter: EOF


# TERMINAL
- name: Install terminal applications
  tags: terminal
  ansible.builtin.package:
    name:
      - sudo
    state: present

# SERVICES
- name: Enable and start serial connection service for kingdomkey
  tags: services
  when: ansible_hostname == 'kingdomkey'
  ansible.builtin.service:
    name: serial-getty@ttyS0.service
    state: started
    enabled: true
