# PATH =  /etc/netplan/
# CONTEXT = ubuntu network config file
# CHANGE =  configure network with dhcp and a vlan, in this case 107

# This is the network config written by 'subiquity'network:
  ethernets:
  ens18:
    dhcp4: false

  vlans:
    vlan107:
      link: ens18
      id: 107
      dhcp4: true
  version: 2